# Generated by Django 4.2.25 on 2025-10-23 11:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ckeditor', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
