# Generated by Django 4.2.25 on 2025-10-23 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0003_application_vacancy_delete_page_application_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
