# Generated by Django 4.2.25 on 2025-10-24 13:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0005_weself'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='weself',
            options={'verbose_name': 'o nas', 'verbose_name_plural': 'o nas'},
        ),
        migrations.AddField(
            model_name='application',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Комментарий кандидата', null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Условия работы', null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Требования к кандидату', null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Обязанности кандидата', null=True),
        ),
    ]
