# Generated by Django 4.2.25 on 2025-10-25 13:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0006_alter_application_options_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('house_working', models.CharField(default='Пн–Пт: 9:00–18:00, Сб–Вс: выходной', help_text='rejim kompany raboty', max_length=200)),
            ],
            options={
                'verbose_name': 'rejim raboty',
                'verbose_name_plural': 'rejim raboty',
            },
        ),
        migrations.RemoveField(
            model_name='weself',
            name='linkedin_link',
        ),
        migrations.AddField(
            model_name='weself',
            name='img',
            field=models.FileField(default='images/default.png', upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='weself',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='about company, selyah i komande'),
        ),
        migrations.AlterField(
            model_name='weself',
            name='tools',
            field=models.CharField(default='Python, Django, Java, HTML, CSS, JavaScript, PostgreSQL', help_text='Инструменты , kotorie vy ispolzuete', max_length=300),
        ),
    ]
