# Generated by Django 4.2.25 on 2025-10-25 17:57

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0007_freeconsultation_remove_weself_linkedin_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Основное описание')),
                ('section1_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока 1')),
                ('section1_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент блока 1')),
                ('section2_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока 2')),
                ('section2_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент блока 2')),
                ('section3_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока 3')),
                ('section3_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент блока 3')),
                ('section4_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока 4')),
                ('section4_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент блока 4')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Страница UX/UI дизайна',
                'verbose_name_plural': 'Страницы UX/UI дизайна',
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'zayavka na vakansi', 'verbose_name_plural': 'zayavka na vakansi'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'vsksnsi', 'verbose_name_plural': 'vakansi'},
        ),
        migrations.AlterField(
            model_name='application',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, help_text='kommentarii kondidata', null=True),
        ),
    ]
