# Generated by Django 4.2.25 on 2025-10-28 10:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0008_designpage_alter_application_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'все проекты',
                'verbose_name_plural': 'все проекты',
            },
        ),
        migrations.AlterModelOptions(
            name='designpage',
            options={'verbose_name': 'stranitsa UX/UI dizayn', 'verbose_name_plural': 'stranitsa UX/UI dizayn'},
        ),
        migrations.AlterModelOptions(
            name='weself',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterField(
            model_name='designpage',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='osnovnoe opisanie'),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section1_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='kontent bloka 1'),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section1_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='zagalovka blok 1'),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section2_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='kontent bloka 2'),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section2_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='zagalovka blok 2'),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section3_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='kontent bloka 3'),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section3_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='zagalovka blok  3'),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section4_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='kontent bloka 4'),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section4_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='zagalovka blok 4'),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='zagolovok stranitsa'),
        ),
    ]
