# Generated by Django 4.2 on 2025-10-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0010_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'registratsiya',
                'verbose_name_plural': 'registratsiya',
            },
        ),
    ]
