# Generated by Django 4.2 on 2025-11-04 11:40

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import telegram_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0011_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allproject',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'application', 'verbose_name_plural': 'applications'},
        ),
        migrations.AlterModelOptions(
            name='designpage',
            options={'verbose_name': 'Design Page', 'verbose_name_plural': 'Design Pages'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='freeconsultation',
            options={'verbose_name': 'Free Consultation', 'verbose_name_plural': 'Free Consultations'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Register', 'verbose_name_plural': 'Register'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'vacancy', 'verbose_name_plural': 'vacancies'},
        ),
        migrations.AlterModelOptions(
            name='weself',
            options={'verbose_name': 'WeSelf', 'verbose_name_plural': 'WeSelf'},
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.CharField(default='example@example.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[telegram_app.models.validate_resume], verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='application',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section1_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section1_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section2_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section2_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section3_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section3_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section4_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='section4_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='designpage',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='requirements',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='freeconsultation',
            name='house_working',
            field=models.CharField(default='Пн–Пт: 9:00–18:00, Сб–Вс: выходной', max_length=200),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='conditions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weself',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='weself',
            name='tools',
            field=models.CharField(default='Python, Django, Java, HTML, CSS, JavaScript, PostgreSQL', max_length=300),
        ),
    ]
