# Generated by Django 4.2 on 2025-11-06 10:35

from django.db import migrations, models
import telegram_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0012_alter_allproject_options_alter_application_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('map_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='resume',
        ),
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[telegram_app.models.validate_resume], verbose_name='Резюме'),
        ),
    ]
